// frontend/src/components/Browser.svelte
<script lang="ts">
    import {Button, Modal, P} from "flowbite-svelte";
    import { Table, TableBody, TableBodyCell, TableBodyRow, TableHead, TableHeadCell } from "flowbite-svelte";
    import {ChangeDirectory, Close, ListDirectory} from "../../wailsjs/go/main/App";

    let {onDisconnect} = $props();
    let listings = $state([]);
    let error = $state("");
    let open = $state(false);

    async function refresh() {
        let contents = await ListDirectory();

        contents.sort((a, b) => {
            if (a.IsDir && !b.IsDir) return -1;
            if (!a.IsDir && b.IsDir) return 1;
            return a.Name.localeCompare(b.Name);
        });

        listings = contents;
    }

    async function changeDir(dir: string) {
        try {
            await ChangeDirectory(dir);
            await refresh();
        } catch (e) {
            error = e;
            open = true;
        }
    }

    async function disconnect() {
        await Close();
        onDisconnect();
    }

    refresh();
</script>

<div class="relative h-screen">
    <div class="overflow-y-auto max-h-[calc(100%-80px)]">
        <Table striped={true}>
            <TableHead>
                <TableHeadCell>Name</TableHeadCell>
                <TableHeadCell>Directory</TableHeadCell>
                <TableHeadCell>Permissions</TableHeadCell>
                <TableHeadCell>Size</TableHeadCell>
                <TableHeadCell>
                    <span class="sr-only">Actions</span>
                </TableHeadCell>
            </TableHead>
            <TableBody>
                <TableBodyRow>
                    <TableBodyCell>..</TableBodyCell>
                    <TableBodyCell>True</TableBodyCell>
                    <TableBodyCell>N/A</TableBodyCell>
                    <TableBodyCell>N/A</TableBodyCell>
                    <TableBodyCell>
                        <button onclick={() => changeDir("..")}
                                class="text-primary-600 dark:text-primary-500 font-medium hover:underline">Open</button>
                    </TableBodyCell>
                </TableBodyRow>

                {#each listings as item}
                    <TableBodyRow>
                        <TableBodyCell>{item.Name}</TableBodyCell>
                        <TableBodyCell>{item.IsDir ? "True" : "False"}</TableBodyCell>
                        <TableBodyCell>{item.Perms}</TableBodyCell>
                        <TableBodyCell>{item.Size}</TableBodyCell>
                        <TableBodyCell>
                            {#if item.IsDir}
                                <button onclick={() => changeDir(item.Name)}
                                        class="text-primary-600 dark:text-primary-500 font-medium hover:underline">Open</button>
                            {:else}
                                <button class="text-primary-600 dark:text-primary-500 font-medium hover:underline">Download</button>
                            {/if}
                        </TableBodyCell>
                    </TableBodyRow>
                {/each}
            </TableBody>
        </Table>
    </div>

    <div class="absolute bottom-0">
        <div class="p-4">
            <Button onclick={disconnect}>Disconnect</Button>
            <Button onclick={refresh}>Refresh</Button>
        </div>
    </div>
</div>


<Modal title="An error has occurred" form bind:open={open}>
    <P>{error}</P>

    <Button type="submit">Ok</Button>
</Modal>

// frontend/src/pages/browser.tsx
import {useEffect, useState} from "preact/hooks";
import {ChangeDirectory, Close, ListDirectory} from "../../wailsjs/go/main/App";
import {ftpclient} from "../../wailsjs/go/models";
import FtpEntry = ftpclient.FtpEntry;
import {Button, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow} from "@mui/material";
import {useLocation} from "preact-iso";

export function BrowserPage(props: any) {
    const [dir, setDir] = useState<FtpEntry[]>([]);
    const location = useLocation();

    useEffect(() => {
        refresh().then();
    }, []);

    const disconnect = async () => {
        await Close();
        location.route('/');
    }

    const cd = async (path: string) => {
        try {
            await ChangeDirectory(path);
        } catch (e) {
            console.error(e);
        }
        await refresh()
        console.log(dir);
    }

    const refresh = async () => {
        try {
            setDir(await ListDirectory());
        } catch (e) {
            console.error(e);
        }
    }

    return (
        <>
            <div className="flex flex-col gap-4" style={{height: "calc(100vh - 128px)"}}>
                <TableContainer component={Paper}>
                    <Table sx={{ minWidth: 650 }} aria-label="simple table">
                        <TableHead>
                            <TableRow>
                                <TableCell>Name</TableCell>
                                <TableCell align="right">Directory</TableCell>
                                <TableCell align="right">Permissions</TableCell>
                                <TableCell align="right">Size</TableCell>
                                <TableCell align="right">Actions</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            <TableRow
                                key={'..'}
                                sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                            >
                                <TableCell component="th" scope="row">
                                    ..
                                </TableCell>
                                <TableCell align="right">True</TableCell>
                                <TableCell align="right">N/A</TableCell>
                                <TableCell align="right">N/A</TableCell>
                                <TableCell align="right">
                                    <Button variant="contained" onClick={() => cd("..")}>Open</Button>
                                </TableCell>
                            </TableRow>

                            {dir.map((entry) => (
                                <TableRow
                                    key={entry.Name}
                                    sx={{ '&:last-child td, &:last-child th': { border: 0 } }}
                                >
                                    <TableCell component="th" scope="row">
                                        {entry.Name}
                                    </TableCell>
                                    <TableCell align="right">{entry.IsDir ? "True" : "False"}</TableCell>
                                    <TableCell align="right">{entry.Perms}</TableCell>
                                    <TableCell align="right">{entry.IsDir ? "N/A" : entry.Size}</TableCell>
                                    <TableCell align="right">
                                        {entry.IsDir ? <Button variant="contained" onClick={() => cd(entry.Name)}>Open</Button> :
                                            <Button variant="contained">Download</Button>}
                                    </TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </TableContainer>
            </div>

            <Button variant="contained" onClick={disconnect}>Disconnect</Button>
            <Button variant="contained" onClick={refresh}>Refresh</Button>
        </>
    )
}
